### get users
GET http://localhost:5000/account/users/

### add stolen bike
POST http://localhost:5000/case/stolen_bike/ HTTP/1.1
Content-Type: application/json

{
    "brand": "marca",
    "model": "modelo x",
    "license":"XL-5200",
    "color": "Yellow and blue",
    "type": "classic",
    "desc": "the front tire is white",
    "owner": "63179966ddcecb10635674d8"
}

### get bike back
GET http://localhost:5000/case/recovery_bike/6317a7745ceee9f330f3c59f