### get departments
GET http://localhost:5000/department/


### register new department
POST http://localhost:5000/department/new_department/ HTTP/1.1
Content-Type: application/json

{
    "name": "Dep Telde",
    "city": "Las Palmas de GC"
}

### add police officer to department
POST http://localhost:5000/department/add_police_officer HTTP/1.1
Content-Type: application/json

{
	"departmentId":"631f2e9ba1ad6d0cedd33ebf", 
	"officerId":"631f2db9a1ad6d0cedd33eb8"
}

### remove police officer
POST http://localhost:5000/department/remove_police_officer HTTP/1.1
Content-Type: application/json

{
		"policeOfficerId":"631f2db9a1ad6d0cedd33eb8"
}