### get users
GET http://localhost:5000/police/officers

### get free agents
GET http://localhost:5000/police/free_agents

### register police officer
POST http://localhost:5000/auth/police/signup/ HTTP/1.1
Content-Type: application/json

{
    "email": "police2@police.com",
    "fullname": "Marco Pin",
    "phone":"928 654 130",
    "password": "password",
    "address": "calle falsa 127"
}

### release police from case
POST http://localhost:5000/police/release/ HTTP/1.1
Content-Type: application/json

{
    "policeOfficerId": "6315f5d97e1a85b48ceece05"
}