### get users
GET http://localhost:5000/account/users/

### get user
GET http://localhost:5000/account/632368577c96b3376e371e78/

### get bikes of a user
GET http://localhost:5000/account/users/bikes/6318ab26e7acbe19e2e9a302

### register new user
POST http://localhost:5000/auth/signup/ HTTP/1.1
Content-Type: application/json

{
    "email": "patriosweb@gmail.com",
    "fullname": "Patrios",
    "phone":"928 654 130",
    "password": "password",
    "currentLocation": {"lat":20.55, "lng":-55.96},
    "address": "mi casa"
}

### login
POST http://localhost:5000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "patriosweb@gmail.com",
    "password": "password"
}

### update password
PATCH http://localhost:5000/account/change-password/631f29d7824cbf68693bcdec HTTP/1.1
Content-Type: application/json

{
    "oldPassword": "password",
    "newPassword": "pass"
}